import { Router } from 'express';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { z } from 'zod';
import { globalRateLimit } from '../rate-limit/middleware.js';
import { requireAdminMfa } from '../auth/middleware.js';
import { log } from '../util/log.js';

export const localAgentRouter = Router();
const __dirname = path.dirname(fileURLToPath(import.meta.url));
let runtimeLocalAgentEnabled = false;

const BootstrapLocalAgentBody = z.object({
  os: z.enum(['windows', 'linux']).optional(),
});

const ExecuteEnableNetworksBody = z.object({
  // RFC 952 / RFC 1123: labels of [a-z0-9] separated by dots/hyphens; no leading/trailing hyphens.
  hostname: z.string().min(4).max(253).regex(
    /^[a-zA-Z0-9]([a-zA-Z0-9._-]*[a-zA-Z0-9])?$/,
    'hostname must contain only letters, digits, hyphens, underscores, and dots',
  ),
  os: z.enum(['windows', 'linux']),
  autostart: z.boolean().default(true),
  overwriteDns: z.boolean().default(false),
  acknowledgeCriticalChanges: z.literal(true),
  // Optional: override the local origin the tunnel forwards to. Derived from the
  // server's PORT env var when not supplied by the client.
  // Restrict to http/https to prevent javascript:, data:, file:// injection into
  // the local-agent-connector configuration.
  localOrigin: z.string().url().refine(
    u => u.startsWith('http://') || u.startsWith('https://'),
    { message: 'localOrigin must use http or https scheme' },
  ).optional(),
});

function envTrue(name: string): boolean {
  return (process.env[name] ?? '').trim().toLowerCase() === 'true';
}

export function isLocalAgentFeatureEnabled(): boolean {
  // Explicit env enable OR runtime bootstrap via admin wizard.
  return envTrue('YTHRIL_LOCAL_AGENT_ENABLED') || runtimeLocalAgentEnabled;
}

function isLoopbackHost(host: string): boolean {
  // Only accept numeric loopback addresses. 'localhost' is intentionally excluded
  // because it is resolved via DNS/hosts and could be remapped to a non-loopback
  // address on a compromised system.
  const h = host.toLowerCase();
  return h === '127.0.0.1' || h === '::1';
}

function getAgentConfig(): { baseUrl: string | null; token: string | null } {
  if (!isLocalAgentFeatureEnabled()) {
    return { baseUrl: null, token: null };
  }

  // Use || not ?? so an empty-string env var falls back to the default loopback URL.
  const raw = process.env['YTHRIL_LOCAL_AGENT_URL']?.trim() || 'http://127.0.0.1:38123';
  let token = process.env['YTHRIL_LOCAL_AGENT_TOKEN']?.trim() || null;
  // Prefer runtime token (pre-generated at spawn); fall back to token file.
  if (!token) token = runtimeConnectorToken;
  if (!token) {
    const tokenFile = process.env['YTHRIL_LOCAL_AGENT_TOKEN_FILE']?.trim()
      || path.join(os.homedir(), '.ythril-local-connector', 'token');
    if (tokenFile) {
      try {
        const fromFile = fs.readFileSync(tokenFile, 'utf8').trim();
        token = fromFile || null;
      } catch {
        // token file not yet created — connector will create it on first start
      }
    }
  }
  if (!raw) return { baseUrl: null, token };

  let parsed: URL;
  try {
    parsed = new URL(raw);
  } catch {
    log.warn('Local agent URL is invalid; feature will remain unavailable.');
    return { baseUrl: null, token };
  }

  const allowRemote = envTrue('YTHRIL_LOCAL_AGENT_ALLOW_REMOTE');
  if (!allowRemote && !isLoopbackHost(parsed.hostname)) {
    log.warn('Local agent URL rejected: non-loopback host while YTHRIL_LOCAL_AGENT_ALLOW_REMOTE is not true.');
    return { baseUrl: null, token };
  }

  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    log.warn('Local agent URL rejected: protocol must be http/https.');
    return { baseUrl: null, token };
  }

  // Remote mode normally requires HTTPS to protect the bearer token in transit.
  // YTHRIL_LOCAL_AGENT_ALLOW_INSECURE=true is an escape hatch for Docker workstation
  // mode where host-gateway is the Docker bridge (effectively localhost) — the
  // connection never leaves the machine, so TLS is unnecessary overhead.
  const allowInsecure = envTrue('YTHRIL_LOCAL_AGENT_ALLOW_INSECURE');
  if (allowRemote && !allowInsecure && parsed.protocol !== 'https:') {
    log.warn('Local agent URL rejected: remote mode requires https (set YTHRIL_LOCAL_AGENT_ALLOW_INSECURE=true to allow HTTP for Docker workstation mode).');
    return { baseUrl: null, token };
  }

  const baseUrl = raw.endsWith('/') ? raw.slice(0, -1) : raw;
  return { baseUrl, token };
}

// Token pre-generated by the server and injected into the connector via env var.
// This eliminates the token-file timing race on first startup.
let runtimeConnectorToken: string | null = null;

async function waitForAgentReady(maxAttempts = 60, delayMs = 500): Promise<boolean> {
  for (let i = 0; i < maxAttempts; i++) {
    try {
      const r = await callAgent('/v1/status', { method: 'GET' });
      if (r.ok) return true;
      // Non-200 from a live connector (e.g. 401 during startup) — keep trying.
      log.info(`[local-agent] ready-poll ${i + 1}: HTTP ${r.status}`);
    } catch (err) {
      // Connection refused / ECONNREFUSED — connector not listening yet, keep trying.
      if (i % 5 === 0) {
        log.info(`[local-agent] ready-poll ${i + 1}: ${err instanceof Error ? err.message : String(err)}`);
      }
    }
    await new Promise(resolve => setTimeout(resolve, delayMs));
  }
  return false;
}

function getOrCreateConnectorToken(): string {
  const connectorDir = path.join(os.homedir(), '.ythril-local-connector');
  const tokenFile = path.join(connectorDir, 'token');
  // Reuse an existing token so a still-running connector from a previous session
  // continues to authenticate correctly — no zombie/token-mismatch issues.
  try {
    const existing = fs.readFileSync(tokenFile, 'utf8').trim();
    if (existing) return existing;
  } catch { /* file not yet created */ }
  // Generate once and persist.
  const token = crypto.randomBytes(48).toString('base64url');
  try {
    fs.mkdirSync(connectorDir, { recursive: true, mode: 0o700 });
    fs.writeFileSync(tokenFile, token + '\n', { encoding: 'utf8', mode: 0o600 });
  } catch (e) {
    log.warn(`[local-agent] could not write token file: ${e instanceof Error ? e.message : String(e)}`);
  }
  return token;
}

const CONNECTOR_PID_FILE = path.join(os.homedir(), '.ythril-local-connector', 'server.pid');

function killStaleConnector(): void {
  try {
    const raw = fs.readFileSync(CONNECTOR_PID_FILE, 'utf8').trim();
    const pid = Number(raw);
    if (!Number.isFinite(pid) || pid <= 0) return;
    try {
      process.kill(pid, 'SIGTERM');
      log.info(`[local-agent] killed stale connector process (pid ${pid})`);
    } catch {
      // Process already gone — that's fine.
    }
  } catch {
    // PID file doesn't exist yet.
  }
}

function spawnConnector(entry: string, tsx?: string): void {
  const connectorDir = path.join(os.homedir(), '.ythril-local-connector');
  const logFile = path.join(connectorDir, 'connector.log');
  try { fs.mkdirSync(connectorDir, { recursive: true, mode: 0o700 }); } catch { /* ignore */ }

  // Kill any stale connector before spawning so it doesn't hold the port.
  killStaleConnector();

  // Reuse or create a persistent token — keeps working across server restarts.
  const token = getOrCreateConnectorToken();
  runtimeConnectorToken = token;

  const cmd = tsx ?? process.execPath;
  const args = tsx ? [tsx, entry] : [entry];
  let outFd: number | undefined;
  let errFd: number | undefined;
  try {
    outFd = fs.openSync(logFile, 'a');
    errFd = fs.openSync(logFile, 'a');
  } catch { /* fall back to ignore */ }

  const child = spawn(cmd, args, {
    detached: true,
    stdio: ['ignore', outFd ?? 'ignore', errFd ?? 'ignore'],
    windowsHide: true,
    // Inject token via env so connector uses it immediately without waiting for file.
    env: { ...process.env, YTHRIL_CONNECTOR_TOKEN: token },
  });
  child.on('error', (err) => log.warn(`[local-agent] connector spawn error: ${err.message}`));
  if (child.pid) {
    try { fs.writeFileSync(CONNECTOR_PID_FILE, String(child.pid), { encoding: 'utf8', mode: 0o600 }); } catch { /* ignore */ }
  }
  log.info(`[local-agent] connector spawned (pid ${child.pid ?? '?'}), log: ${logFile}`);
  child.unref();
}

function tryStartLocalConnector(): void {
  const jsEntry = path.resolve(__dirname, '..', 'local-agent-connector', 'index.js');
  const tsEntry = path.resolve(__dirname, '..', 'local-agent-connector', 'index.ts');

  if (fs.existsSync(jsEntry)) {
    log.info(`[local-agent] starting connector (compiled): ${jsEntry}`);
    spawnConnector(jsEntry);
  } else if (fs.existsSync(tsEntry)) {
    // Dev mode — tsx lives in repo root node_modules (hoisted).
    const tsxCli = path.resolve(__dirname, '..', '..', '..', 'node_modules', 'tsx', 'dist', 'cli.mjs');
    if (!fs.existsSync(tsxCli)) {
      log.warn(`[local-agent] tsx not found at ${tsxCli} — start connector manually: npm run local-connector:dev`);
      return;
    }
    log.info(`[local-agent] starting connector (dev/tsx): ${tsEntry}`);
    spawnConnector(tsEntry, tsxCli);
  } else {
    log.warn(`[local-agent] connector entry not found — jsEntry=${jsEntry}, tsEntry=${tsEntry}`);
  }
}

localAgentRouter.post('/bootstrap', globalRateLimit, requireAdminMfa, async (req, res) => {
  const parsed = BootstrapLocalAgentBody.safeParse(req.body ?? {});
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }

  log.info('[local-agent] bootstrap requested');
  runtimeLocalAgentEnabled = true;

  // If already reachable, return quickly.
  try {
    const ping = await callAgent('/v1/status', { method: 'GET' });
    if (ping.ok) {
      log.info('[local-agent] connector already running — returning early');
      res.json({ ok: true, message: 'Local connector already running.' });
      return;
    }
    log.info(`[local-agent] pre-ping returned HTTP ${ping.status} — proceeding to spawn`);
  } catch (pingErr) {
    log.info(`[local-agent] pre-ping failed (expected if not running): ${pingErr instanceof Error ? pingErr.message : String(pingErr)}`);
  }

  try {
    // Only attempt to spawn the connector when the URL is loopback — i.e. the server
    // is running natively on the same machine (workstation dev mode).
    // When YTHRIL_LOCAL_AGENT_URL points to host-gateway (Docker mode), the connector
    // runs on the host OS and cannot be spawned from inside the container.
    const cfg = getAgentConfig();
    const isLoopbackTarget = cfg.baseUrl !== null && new URL(cfg.baseUrl).hostname === '127.0.0.1';
    if (isLoopbackTarget) {
      tryStartLocalConnector();
      log.info('[local-agent] spawn attempted, waiting for ready...');
    } else {
      log.info('[local-agent] remote connector URL — skipping spawn, checking reachability...');
    }
    const ready = await waitForAgentReady();
    if (!ready) {
      log.warn('[local-agent] connector did not become ready in time');
      const hint = isLoopbackTarget
        ? 'The connector process could not start. Check the server log for spawn errors.'
        : 'Start the local connector on this machine: run `npm run local-connector:start` in the Ythril server directory, then try again.';
      res.status(502).json({ error: hint });
      return;
    }
    log.info('[local-agent] connector is ready');
    res.json({ ok: true, message: 'Local connector bootstrapped and reachable.' });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    log.warn(`local-agent bootstrap failed: ${msg}`);
    res.status(502).json({ error: `Local agent bootstrap failed: ${msg}` });
  }
});

async function callAgent(path: string, init: RequestInit = {}, timeoutMs = 15_000): Promise<Response> {
  const cfg = getAgentConfig();
  if (!cfg.baseUrl) throw new Error('Local agent is not configured');

  const headers = new Headers(init.headers ?? {});
  if (cfg.token) headers.set('Authorization', `Bearer ${cfg.token}`);

  return fetch(`${cfg.baseUrl}${path}`, {
    ...init,
    headers,
    signal: AbortSignal.timeout(timeoutMs),
  });
}

localAgentRouter.get('/status', globalRateLimit, requireAdminMfa, async (_req, res) => {
  if (!isLocalAgentFeatureEnabled()) {
    // Return 200 so the client can distinguish "disabled" from a network error and display a helpful message
    res.json({
      configured: false,
      reachable: false,
      canExecute: false,
      message: 'Local connector is not enabled on this server. Use the manual commands — copy and run them on this machine, then click "I finished setup".',
    });
    return;
  }

  const cfg = getAgentConfig();
  if (!cfg.baseUrl) {
    // Should not happen during wizard flow — baseUrl is always set to 127.0.0.1:38123
    // unless YTHRIL_LOCAL_AGENT_URL is explicitly set to an invalid/remote value.
    res.json({
      configured: false,
      reachable: false,
      canExecute: false,
      message: 'Local connector URL is misconfigured. Check the YTHRIL_LOCAL_AGENT_URL server environment variable.',
    });
    return;
  }

  try {
    const r = await callAgent('/v1/status', { method: 'GET' });
    if (!r.ok) {
      const text = await r.text();
      res.json({
        configured: true,
        reachable: false,
        canExecute: false,
        message: `Agent status check failed (${r.status}): ${text || 'no response body'}`,
      });
      return;
    }

    const body = await r.json().catch(() => ({}));
    res.json({
      configured: true,
      reachable: true,
      canExecute: true,
      message: typeof body?.message === 'string' ? body.message : 'Local agent reachable.',
      agent: body,
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    res.json({
      configured: true,
      reachable: false,
      canExecute: false,
      message: `Local agent unreachable: ${msg}`,
    });
  }
});

localAgentRouter.post('/enable-networks/execute', globalRateLimit, requireAdminMfa, async (req, res) => {
  if (!isLocalAgentFeatureEnabled()) {
    res.status(404).json({ error: 'Local agent feature is disabled' });
    return;
  }

  const parsed = ExecuteEnableNetworksBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }

  try {
    // 5-minute timeout: cloudflared tunnel login opens a browser and blocks until
    // the user authorises the Cloudflare connection — that can take several minutes.
    // Inject localOrigin from the server's own PORT env so the connector writes the
    // correct origin into cloudflared config.yml regardless of what port Ythril runs on.
    // YTHRIL_LOCAL_AGENT_ORIGIN overrides this — needed in Docker workstation mode where
    // the container's internal PORT (3200) differs from the host-exposed port (e.g. 3210).
    const serverPort = Number(process.env['PORT'] ?? 3200);
    const defaultOrigin = process.env['YTHRIL_LOCAL_AGENT_ORIGIN']?.trim()
      || `http://localhost:${serverPort}`;
    const bodyWithOrigin = {
      ...parsed.data,
      localOrigin: parsed.data.localOrigin ?? defaultOrigin,
    };
    const response = await callAgent('/v1/actions/enable-networks', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(bodyWithOrigin),
    }, 5 * 60 * 1_000);

    const raw = await response.text();
    const body = raw ? JSON.parse(raw) : {};

    if (!response.ok) {
      res.status(502).json({
        error: body?.error ?? `Local agent returned HTTP ${response.status}`,
      });
      return;
    }

    res.json({
      ok: true,
      ...body,
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    log.warn(`local-agent execute failed: ${msg}`);
    res.status(502).json({ error: `Local agent execution failed: ${msg}` });
  }
});
